<?php
$z[0]=Array("field","",161,189);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",191,220);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",240,272);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("arclist","\r\n        <div class=\"item course-item\"> <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n          <div class=\"down-content\">\r\n            <div class=\"price-red\"> <span>Gold</span>\r\n              <div class=\"base\"></div>\r\n            </div>\r\n            <h4 class=\"iport-title\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n            <p class=\"desc\">[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            <div class=\"text-button\"> <a href=\"[field:arcurl/]\">查看更多<i class=\"fa fa-arrow-right\"></i></a> </div>\r\n          </div>\r\n        </div>\r\n        ",349,1056);
$z[3][4]=array();
$z[3][4]['row']="12";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>