<li class="first-slide" data-transition="fade" data-slotamount="10" data-masterspeed="300" > <img src="[field:picname/]" data-fullwidthcentering="on" alt="[field:title/]"/>
          <div class="tp-caption first-line lft tp-resizeme start" data-x="center" data-hoffset="0" data-y="190" data-speed="1000" data-start="200" data-easing="Power4.easeOut" data-splitin="none" data-splitout="none" data-elementdelay="0" data-endelementdelay="0">
            <div class="slide-caption"> <a href="#1"><i class="fa fa-info-circle"></i></a> <a href="#[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global]"><span>[field:shorttitle/]</span></a>
              <h2>[field:title/]</h2>
              <p>[field:description/]</p>
            </div>
          </div>
        </li>