<div class="item course-item"> <a href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]"/></a>
          <div class="down-content">
            <div class="price-red"> <span>Gold</span>
              <div class="base"></div>
            </div>
            <h4 class="iport-title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
            <p class="desc">[field:description function="cn_substr(@me,200)"/]...</p>
            <div class="text-button"> <a href="[field:arcurl/]">查看更多<i class="fa fa-arrow-right"></i></a> </div>
          </div>
        </div>