<div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12 iwt-img"> <a href="[field:typelink/]"><img src="/skin/images/iw-1.jpg"/></a> </div>
              <div class="col-md-6 col-xs-6 iwt-L-img"> <a href="[field:typelink/]"><img src="/skin/images/iw-2.jpg"/></a> </div>
              <div class="col-md-6 col-xs-6 iwt-R-img"> <a href="[field:typelink/]"><img src="/skin/images/iw-3.jpg"/></a> </div>
            </div>