<?php  exit();
/*
Page: /dede/
Error: Table 'dedepucom57uft8.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-02-08 22:32:28
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'dedepucom57uft8.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-02-08 22:32:28
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'dedepucom57uft8.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2019-02-08 22:32:28
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'dedepucom57uft8.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2019-02-08 22:32:28
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'dedepucom57uft8.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2019-02-08 22:32:28
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=get_seo
Error: Table 'dedepucom57uft8.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2019-02-08 22:32:28
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=10
Error: Table 'dedepucom57uft8.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-02-08 22:32:37
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'dedepucom57uft8.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2019-02-08 22:32:38
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'dedepucom57uft8.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2019-02-08 22:32:38
*/
?>
<?php  exit();
/*
Page: /dede/sys_data.php
Error: Table 'dedepucom57uft8.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT addtable FROM `dede_channeltype` </font>
Time2019-02-08 22:32:39
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='9' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='35' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='36' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='37' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='38' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='39' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(1,1) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(5,5) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(16,16) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  reid=0 AND ispart<>2 AND ishidden<>1 AND channeltype>0  ORDER BY sortrank ASC LIMIT 20</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='9' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='9' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath
          From `dede_arctype` WHERE reid=0 And ishidden<>1 order by sortrank asc    </font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typedir,typenameen,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='17' LIMIT 0,1;</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  reid=0 AND ispart<>2 AND ishidden<>1 AND channeltype>0  ORDER BY sortrank ASC LIMIT 20</font>
Time2019-06-27 11:23:58
*/
?>
<?php  exit();
/*
Page: /dede/
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:24:18
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:24:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'dongchengweiye.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2019-06-27 11:24:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'dongchengweiye.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2019-06-27 11:24:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2019-06-27 11:24:19
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'dongchengweiye.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2019-06-27 11:24:20
*/
?>
<?php  exit();
/*
Page: /dede/index_body.php?dopost=getRightSide
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2019-06-27 11:24:20
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=3
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:24:22
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=5
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:24:23
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=6
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:24:27
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=7
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:25:16
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=10
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:25:16
*/
?>
<?php  exit();
/*
Page: /dede/index_menu.php
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:26:00
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=5
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:26:09
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=3
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:26:10
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=6
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:26:13
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=7
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:26:14
*/
?>
<?php  exit();
/*
Page: /dede/index_menu_load.php?openitem=10
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2019-06-27 11:26:17
*/
?>
<?php  exit();
/*
Page: /dede/sys_data.php
Error: Table 'dongchengweiye.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT addtable FROM `dede_channeltype` </font>
Time2019-06-27 11:26:42
*/
?>
