<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Lia5Yqh6IyD5Zu0');
$cfg_Cs[2]=array(1,1,1,'5YWa5pS/5bmy6YOo5Z+56K6t');
$cfg_Cs[3]=array(1,1,1,'5a2m5Y6G5pWZ6IKy');
$cfg_Cs[4]=array(1,1,1,'6KGM5Lia5oqA5pyv5Z+56K6t');
$cfg_Cs[5]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[8]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[9]=array(8,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[11]=array(8,1,1,'5YWs5Y+455u45YaM');
$cfg_Cs[16]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[17]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[20]=array(0,1,1,'6aaW6aG15bm754Gv');
?>